### ISSUE TITLE
Some error with meta data

### ISSUE THREAD

**Issue by iAmIlluminati** [amine0110/nifti2dicom#3]
I converted a .nii file to dicom. It is a volumetric scan,  using `nifti2dicom_1file(input_path,output_path)` but when i tried to view it using https://www.imaios.com/en/imaios-dicom-viewer , I could see one slice at a time and it recognises each .dcm as a separate scan instead of a sequence.  But it works fine in converting when I use a online tool like https://www.onlineconverter.com/nifti-to-dicom . How to fix this and programmatically generate the DICOM ?

**Comment by amine0110** [comment]
Hi,

Yes this code is not very precise for this conversion, I created something more accurate and fixes this error of indexation. Please find it in this repo: https://github.com/amine0110/Medical-Conversions

The most important part for you is from here: https://github.com/amine0110/Medical-Conversions/blob/main/functions.py#L54

Happy learning
